const AllProductsData = [
  {
    id: 1,
    category: "sweater",
    gendercategory: "women",
    image: "images/product_01.jpg",
    hoverimage: "images/product_01b.jpg",
    title: "Sweater in Tosca",
    price: 45,
    quantity: 10,
    color: "Green",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 2,
    category: "sweater",
    gendercategory: "women",
    image: "images/product_02.jpg",
    hoverimage: "images/product_02b.jpg",
    title: "Royal Blue",
    price: 40,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 3,
    category: "shirt",
    gendercategory: "women",
    image: "images/product_03.jpg",
    hoverimage: "images/product_03b.jpg",
    title: "Teal Blue Shirt",
    price: 50,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 4,
    category: "hoodie",
    gendercategory: "women",
    image: "images/product_04.jpg",
    hoverimage: "images/product_04b.jpg",
    title: "Weird Blue",
    price: 35,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 5,
    category: "hoodie",
    gendercategory: "women",
    image: "images/product_05.jpg",
    hoverimage: "images/product_05b.jpg",
    title: "Baby Blue",
    price: 35,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 6,
    category: "sweater",
    gendercategory: "women",
    image: "images/product_06.jpg",
    hoverimage: "images/product_06b.jpg",
    title: "Brown Mundey",
    price: 35,
    quantity: 10,
    color: "Brown",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 7,
    category: "hoodie",
    gendercategory: "women",
    image: "images/product_07.jpg",
    hoverimage: "images/product_07b.jpg",
    title: "Baby Pink",
    price: 35,
    quantity: 10,
    color: "Pink",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 8,
    category: "sweater",
    gendercategory: "women",
    image: "images/product_08.jpg",
    hoverimage: "images/product_08b.jpg",
    title: "Woolen Maroon Sweater",
    price: 40,
    quantity: 10,
    color: "Maroon",
    size: ["s", "m", "l", "xl", "xxl"],
  },
];

const NewProductsData = [
  {
    id: 1,
    category: "sweater",
    gendercategory: "women",
    image: "images/product_01.jpg",
    hoverimage: "images/product_01b.jpg",
    title: "Sweater in Tosca",
    price: 45,
    quantity: 10,
    color: "Green",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 2,
    category: "sweater",
    gendercategory: "women",
    image: "images/product_02.jpg",
    hoverimage: "images/product_02b.jpg",
    title: "Royal Blue",
    price: 40,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 3,
    category: "shirt",
    gendercategory: "women",
    image: "images/product_03.jpg",
    hoverimage: "images/product_03b.jpg",
    title: "Teal Blue Shirt",
    price: 50,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 4,
    category: "hoodie",
    gendercategory: "women",
    image: "images/product_04.jpg",
    hoverimage: "images/product_04b.jpg",
    title: "Weird Blue",
    price: 35,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 5,
    category: "hoodie",
    gendercategory: "women",
    image: "images/product_05.jpg",
    hoverimage: "images/product_05b.jpg",
    title: "Baby Blue",
    price: 35,
    quantity: 10,
    color: "Blue",
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 6,
    category: "sweater",
    gendercategory: "women",
    image: "images/product_06.jpg",
    hoverimage: "images/product_06b.jpg",
    title: "Brown Mundey",
    price: 35,
    quantity: 10,
    color: "Brown",
    size: ["s", "m", "l", "xl", "xxl"],
  },
];

export { AllProductsData, NewProductsData };
