const AllProductsData = [
  {
    id: 1,
    category: "sweater",
    gendercategory: "women",
    image: "/assets/product_01.jpg",
    hoverimage: "/assets/product_01b.jpg",
    title: "Sweater in Tosca",
    old_price: 60,
    price: 45,
    quantity: 10,
    color: ["Green", "Blue", "Brown", "Pink"],
    size: ["s", "m", "l"],
  },
  {
    id: 2,
    category: "sweater",
    gendercategory: "women",
    image: "/assets/product_02.jpg",
    hoverimage: "/assets/product_02b.jpg",
    title: "Royal Blue",
    old_price: 80,
    price: 60,
    quantity: 10,
    color: ["Blue", "Green"],
    size: ["s", "m", "l", "xxl"],
  },
  {
    id: 3,
    category: "shirt",
    gendercategory: "women",
    image: "/assets/product_03.jpg",
    hoverimage: "/assets/product_03b.jpg",
    title: "Teal Blue Shirt",
    old_price: 100,
    price: 80,
    quantity: 10,
    color: ["Blue","Yellow","Brown"],
    size: ["m", "xl", "xxl"],
  },
  {
    id: 4,
    category: "hoodie",
    gendercategory: "women",
    image: "/assets/product_04.jpg",
    hoverimage: "/assets/product_04b.jpg",
    title: "Weird Blue",
    old_price: 52,
    price: 39,
    quantity: 10,
    color: ["Blue","Yellow","Pink","Green"],
    size: ["s", "m", "l"],
  },
  {
    id: 5,
    category: "hoodie",
    gendercategory: "women",
    image: "/assets/product_05.jpg",
    hoverimage: "/assets/product_05b.jpg",
    title: "Baby Blue",
    old_price: 60,
    price: 45,
    quantity: 10,
    color: ["Blue","Pink","Brown"],
    size: ["l"],
  },
  {
    id: 6,
    category: "sweater",
    gendercategory: "women",
    image: "/assets/product_06.jpg",
    hoverimage: "/assets/product_06b.jpg",
    title: "Brown Mundey",
    old_price: 72,
    price: 54,
    quantity: 10,
    color: ["Brown","Green"],
    size: ["m", "l", "xl"],
  },
  {
    id: 7,
    category: "hoodie",
    gendercategory: "women",
    image: "/assets/product_07.jpg",
    hoverimage: "/assets/product_07b.jpg",
    title: "Baby Pink",
    old_price: 68,
    price: 51,
    quantity: 10,
    color: ["Pink","Maroon","Blue"],
    size: ["s", "m", "l", "xl", "xxl"],
  },
  {
    id: 8,
    category: "sweater",
    gendercategory: "women",
    image: "/assets/product_08.jpg",
    hoverimage: "/assets/product_08b.jpg",
    title: "Deep Long Neck Woolen Maroon Colored Sweater",
    old_price: 65,
    price: 53,
    quantity: 10,
    color: ["Maroon","Tosca"],
    size: ["m", "l", "xl", "xxl"],
  },
  {
    id: 9,
    category: "shirt",
    gendercategory: "men",
    image: "/assets/product_09.jpg",
    hoverimage: "/assets/product_09.jpg",
    title: "Maroon Check Round Necked Black Casual T",
    old_price: 75,
    price: 57,
    quantity: 7,
    color: ["Maroon","White"],
    size: ["m", "l", "xl", "xxl"],
  },
  {
    id: 10,
    category: "shirt",
    gendercategory: "men",
    image: "/assets/product_10.jpg",
    hoverimage: "/assets/product_10.jpg",
    title: "Late Winter Casual Pink Black T",
    old_price: 78,
    price: 60,
    quantity: 10,
    color: ["White","Black"],
    size: ["l", "xl", "xxl"],
  },
  {
    id: 11,
    category: "shirt",
    gendercategory: "men",
    image: "/assets/product_11.jpg",
    hoverimage: "/assets/product_11.jpg",
    title: "Round Necked Bluish Grey Checked Casual T",
    old_price: 80,
    price: 59,
    quantity: 8,
    color: ["Blue","Maroon","White"],
    size: ["l", "xl", "xxl"],
  },
];

const NewProductsData = [
  {
    id: 1,
    category: "sweater",
    gendercategory: "women",
    image: "/assets/product_01.jpg",
    hoverimage: "/assets/product_01b.jpg",
    title: "Sweater in Tosca",
    price: 45,
    quantity: 10,
    color: ["Green", "Blue", "Brown", "Pink"],
    size: ["s", "m", "l"],
  },
  {
    id: 2,
    category: "sweater",
    gendercategory: "women",
    image: "/assets/product_02.jpg",
    hoverimage: "/assets/product_02b.jpg",
    title: "Royal Blue",
    price: 60,
    quantity: 10,
    color: ["Blue", "Green"],
    size: ["s", "m", "l", "xxl"],
  },
  {
    id: 3,
    category: "shirt",
    gendercategory: "women",
    image: "/assets/product_03.jpg",
    hoverimage: "/assets/product_03b.jpg",
    title: "Teal Blue Shirt",
    price: 80,
    quantity: 10,
    color: ["Blue","Yellow","Brown"],
    size: ["m", "xl", "xxl"],
  },
  {
    id: 4,
    category: "hoodie",
    gendercategory: "women",
    image: "/assets/product_04.jpg",
    hoverimage: "/assets/product_04b.jpg",
    title: "Weird Blue",
    price: 39,
    quantity: 10,
    color: ["Blue","Yellow","Pink","Green"],
    size: ["s", "m", "l"],
  },
  {
    id: 5,
    category: "hoodie",
    gendercategory: "women",
    image: "/assets/product_05.jpg",
    hoverimage: "/assets/product_05b.jpg",
    title: "Baby Blue",
    price: 45,
    quantity: 10,
    color: ["Blue","Pink","Brown"],
    size: ["l"],
  },
  {
    id: 6,
    category: "sweater",
    gendercategory: "women",
    image: "/assets/product_06.jpg",
    hoverimage: "/assets/product_06b.jpg",
    title: "Brown Mundey",
    price: 54,
    quantity: 10,
    color: ["Brown","Green"],
    size: ["m", "l", "xl"],
  },
];

export { AllProductsData, NewProductsData };
